// NAS Card v1.0.0 — CC BY-NC 4.0 — BeGiBue
const NAS_CARD_VERSION="1.0.0";
const DEFAULT_NAS_IMAGE="https://raw.githubusercontent.com/BeGiBue/nas_card/main/images/ds720plus.png";

class NasCard extends HTMLElement{
  constructor(){super();this.attachShadow({mode:"open"});this._hass=null;this._config=null;}
  static getStubConfig(){return{
    title:"DS720+",subtitle:"Synology NAS",show_image:true,image_url:"",
    temperature_entity:"sensor.diskstation_temperatur",cpu_entity:"sensor.diskstation_cpu_auslastung_gesamt",memory_entity:"sensor.diskstation_speichernutzung_real",security_entity:"binary_sensor.diskstation_sicherheitsstatus",
    inbound_entity:"sensor.diskstation_download_durchsatz",outbound_entity:"sensor.diskstation_upload_durchsatz",
    volume_title:"Volume 1",volume_percent_entity:"sensor.diskstation_volume_1_verwendetes_volumen",volume_used_entity:"sensor.diskstation_volume_1_belegter_speicherplatz",volume_status_entity:"sensor.diskstation_volume_1_status",
    drive1_title:"Drive 1",drive1_temperature_entity:"sensor.diskstation_drive_1_temperatur",drive1_lifetime_entity:"binary_sensor.diskstation_drive_1_unterhalb_der_mindestrestlebensdauer",drive1_sectors_entity:"binary_sensor.diskstation_drive_1_max_fehlerhafte_sektoren_uberschritten",drive1_status_entity:"sensor.diskstation_drive_1_status",
    drive2_title:"Drive 2",drive2_temperature_entity:"sensor.diskstation_drive_2_temperatur",drive2_lifetime_entity:"binary_sensor.diskstation_drive_2_unterhalb_der_mindestrestlebensdauer",drive2_sectors_entity:"binary_sensor.diskstation_drive_2_max_fehlerhafte_sektoren_uberschritten",drive2_status_entity:"sensor.diskstation_drive_2_status",
    update_title:"DSM Update",update_entity:"update.diskstation_dsm_update",reboot_entity:"button.diskstation_reboot",last_start_entity:"sensor.diskstation_letzter_start",shutdown_entity:"button.diskstation_shutdown"};}
  static getConfigForm(){
    const e=n=>({name:n,selector:{entity:{}}}),t=n=>({name:n,selector:{text:{}}});
    const L={title:"Titel",subtitle:"Untertitel",show_image:"Gerätebild anzeigen",image_url:"Eigenes Gerätebild (URL, optional)",temperature_entity:"Temperatur",cpu_entity:"CPU-Auslastung",memory_entity:"Speichernutzung / RAM",security_entity:"Sicherheitsstatus",inbound_entity:"Inbound / Download",outbound_entity:"Outbound / Upload",volume_title:"Titel",volume_percent_entity:"Verwendetes Volumen (%)",volume_used_entity:"Belegter Speicherplatz",volume_status_entity:"Status",drive1_title:"Titel",drive1_temperature_entity:"Temperatur",drive1_lifetime_entity:"Mindestrestlebensdauer unterschritten",drive1_sectors_entity:"Fehlerhafte Sektoren überschritten",drive1_status_entity:"Status",drive2_title:"Titel",drive2_temperature_entity:"Temperatur",drive2_lifetime_entity:"Mindestrestlebensdauer unterschritten",drive2_sectors_entity:"Fehlerhafte Sektoren überschritten",drive2_status_entity:"Status",update_title:"Titel",update_entity:"Update-Entität",reboot_entity:"Neustart",last_start_entity:"Letzter Start",shutdown_entity:"Herunterfahren"};
    const x=(name,title,schema)=>({type:"expandable",name,title,flatten:true,schema});
    return{schema:[
      x("general","Allgemein",[t("title"),t("subtitle"),{name:"show_image",selector:{boolean:{}}},t("image_url")]),
      x("system","System",[e("temperature_entity"),e("cpu_entity"),e("memory_entity"),e("security_entity")]),
      x("network","Netzwerk",[e("inbound_entity"),e("outbound_entity")]),
      x("volume","Volume",[t("volume_title"),e("volume_percent_entity"),e("volume_used_entity"),e("volume_status_entity")]),
      x("drive1","Laufwerk 1",[t("drive1_title"),e("drive1_temperature_entity"),e("drive1_lifetime_entity"),e("drive1_sectors_entity"),e("drive1_status_entity")]),
      x("drive2","Laufwerk 2",[t("drive2_title"),e("drive2_temperature_entity"),e("drive2_lifetime_entity"),e("drive2_sectors_entity"),e("drive2_status_entity")]),
      x("update","Update",[t("update_title"),e("update_entity")]),x("actions","Aktionen",[e("reboot_entity"),e("last_start_entity"),e("shutdown_entity")])],
      computeLabel:s=>L[s.name],computeHelper:s=>s.name==="image_url"?"Leer = freigestelltes DS720+-Standardbild.":s.name==="volume_percent_entity"?"Prozentwert; Gesamt und Frei werden aus Prozent + belegtem Speicher berechnet.":undefined};
  }
  setConfig(c){this._config={...NasCard.getStubConfig(),...c};this._render();}
  set hass(h){this._hass=h;this._render();} get hass(){return this._hass;}
  getCardSize(){return 15;}
  getGridOptions(){return{columns:12,min_columns:1,max_columns:12};}
  _s(id){return id&&this._hass?.states?.[id];}
  _f(id){const s=this._s(id);if(!s)return"—";try{if(this._hass?.formatEntityState)return this._hass.formatEntityState(s);}catch(e){}return`${s.state}${s.attributes?.unit_of_measurement?` ${s.attributes.unit_of_measurement}`:""}`;}
  _n(id){const s=this._s(id);if(!s)return NaN;const n=Number(String(s.state).replace(",","."));return Number.isFinite(n)?n:NaN;}
  _num(n,u=""){if(!Number.isFinite(n))return"—";const l=this._hass?.locale?.language||navigator.language||"de-DE",d=Math.abs(n)>=100?0:Math.abs(n)>=10?1:2;return`${new Intl.NumberFormat(l,{maximumFractionDigits:d}).format(n)}${u?` ${u}`:""}`;}
  _tone(id){const s=this._s(id);if(!s)return"neutral";const d=s.entity_id?.split(".")[0],v=String(s.state).toLowerCase();if(["unknown","unavailable"].includes(v))return"neutral";if(d==="binary_sensor")return v==="on"?"error":"success";if(d==="update")return v==="on"?"warning":"success";if(/error|fail|bad|critical|fault|degraded|problem/.test(v))return"error";if(/warn|attention|pending/.test(v))return"warning";if(/normal|ok|healthy|good|safe|secure|online|connected|optimal/.test(v))return"success";return"neutral";}
  _v(){const c=this._config,ps=this._s(c.volume_percent_entity),us=this._s(c.volume_used_entity);let p=this._n(c.volume_percent_entity),u=this._n(c.volume_used_entity),pu=ps?.attributes?.unit_of_measurement||"",uu=us?.attributes?.unit_of_measurement||"";if(pu!=="%"&&uu==="%"){[p,u]=[u,p];[pu,uu]=[uu,pu];}if(Number.isFinite(p)&&p<=1&&p>0&&pu!=="%")p*=100;p=Number.isFinite(p)?Math.max(0,Math.min(100,p)):NaN;const total=Number.isFinite(u)&&Number.isFinite(p)&&p>0?u/(p/100):NaN;return{p,u,total,free:Number.isFinite(total)?Math.max(0,total-u):NaN,unit:uu==="%"?"":uu};}
  _e(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
  _more(id){if(id)this.dispatchEvent(new CustomEvent("hass-more-info",{bubbles:true,composed:true,detail:{entityId:id}}));}
  async _press(id){if(!id||!this._hass)return;const d=id.split(".")[0];if(d==="button")return this._hass.callService("button","press",{entity_id:id});if(d==="script")return this._hass.callService("script","turn_on",{entity_id:id});return this._hass.callService("homeassistant","toggle",{entity_id:id});}
  _metric(icon,id,label,tone="neutral"){return`<button class="metric tone-${tone}" data-more="${this._e(id)}"><ha-icon icon="${icon}"></ha-icon><span><b>${this._e(this._f(id))}</b><small>${label}</small></span></button>`;}
  _drive(title,temp,life,sec,status){const dm=(ic,id,l,t)=>`<button class="dm tone-${t}" data-more="${this._e(id)}"><ha-icon icon="${ic}"></ha-icon><span><b>${this._e(this._f(id))}</b><small>${l}</small></span></button>`;return`<section class="panel drive"><div class="dtitle"><ha-icon icon="mdi:harddisk"></ha-icon><b>${this._e(title)}</b></div>${dm("mdi:thermometer",temp,"Temperatur","warning")}${dm("mdi:heart-outline",life,"Restlebensdauer",this._tone(life))}${dm("mdi:format-list-bulleted-square",sec,"Sektoren",this._tone(sec))}${dm("mdi:check-circle-outline",status,"Status",this._tone(status))}</section>`;}
  _render(){if(!this.shadowRoot||!this._config)return;const c=this._config,v=this._v(),p=Number.isFinite(v.p)?v.p:0,img=c.image_url?.trim()||DEFAULT_NAS_IMAGE;
    this.shadowRoot.innerHTML=`<style>${NasCard.css}</style><ha-card><main>
      <section class="panel hero"><div class="title"><span class="ticon"><ha-icon icon="mdi:nas"></ha-icon></span><div><h1>${this._e(c.title)}</h1><p>${this._e(c.subtitle)}</p></div></div>${c.show_image?`<img src="${this._e(img)}" alt="NAS">`:""}<div class="metrics">${this._metric("mdi:thermometer",c.temperature_entity,"Temperatur","primary")}${this._metric("mdi:cpu-64-bit",c.cpu_entity,"CPU")}${this._metric("mdi:memory",c.memory_entity,"RAM","primary")}${this._metric("mdi:shield-check-outline",c.security_entity,"Sicherheitsstatus",this._tone(c.security_entity))}</div></section>
      <section class="net">${this._net("mdi:arrow-down",c.inbound_entity,"Inbound","error")}${this._net("mdi:arrow-up",c.outbound_entity,"Outbound","success")}</section>
      <section class="panel volume"><div class="donut" style="--p:${(p*3.6).toFixed(2)}deg"><div><b>${Number.isFinite(v.p)?this._e(this._num(v.p))+" %":"—"}</b><small>belegt</small></div></div><div class="vdetail"><h2>${this._e(c.volume_title)}</h2><strong>${this._e(Number.isFinite(v.u)?this._num(v.u,v.unit):this._f(c.volume_used_entity))}${Number.isFinite(v.total)?` <em>/ ${this._e(this._num(v.total,v.unit))}</em>`:""}</strong><p><span>Belegt</span><b>${this._e(this._num(v.u,v.unit))}</b><span>Frei</span><b>${this._e(this._num(v.free,v.unit))}</b><span>Gesamt</span><b>${this._e(this._num(v.total,v.unit))}</b></p></div><button class="vstatus tone-${this._tone(c.volume_status_entity)}" data-more="${this._e(c.volume_status_entity)}"><ha-icon icon="mdi:database"></ha-icon><b>${this._e(this._f(c.volume_status_entity))}</b></button></section>
      ${this._drive(c.drive1_title,c.drive1_temperature_entity,c.drive1_lifetime_entity,c.drive1_sectors_entity,c.drive1_status_entity)}${this._drive(c.drive2_title,c.drive2_temperature_entity,c.drive2_lifetime_entity,c.drive2_sectors_entity,c.drive2_status_entity)}
      <button class="panel update tone-${this._tone(c.update_entity)}" data-more="${this._e(c.update_entity)}"><span class="uicon"><ha-icon icon="mdi:update"></ha-icon></span><span><b>${this._e(c.update_title)}</b><small>${this._e(this._f(c.update_entity))}</small></span><strong>${this._e(this._f(c.update_entity))}</strong></button>
      <section class="foot"><button class="panel fcard" data-press="${this._e(c.reboot_entity)}"><span class="ficon"><ha-icon icon="mdi:restart"></ha-icon></span><span><b>Neustart</b><small>NAS neu starten</small></span></button><button class="panel fcard" data-more="${this._e(c.last_start_entity)}"><span class="ficon"><ha-icon icon="mdi:clock-outline"></ha-icon></span><span><b>Letzter Start</b><small>${this._e(this._f(c.last_start_entity))}</small></span></button><button class="panel fcard off" data-press="${this._e(c.shutdown_entity)}"><span class="ficon"><ha-icon icon="mdi:power"></ha-icon></span><span><b>Herunterfahren</b><small>NAS herunterfahren</small></span></button></section>
    </main></ha-card>`;
    this.shadowRoot.querySelectorAll("[data-more]").forEach(x=>x.onclick=()=>this._more(x.dataset.more));this.shadowRoot.querySelectorAll("[data-press]").forEach(x=>x.onclick=()=>this._press(x.dataset.press));}
  _net(icon,id,label,tone){return`<button class="panel ncard tone-${tone}" data-more="${this._e(id)}"><span><ha-icon icon="${icon}"></ha-icon></span><div><small>${label}</small><b>${this._e(this._f(id))}</b></div></button>`;}
  static get css(){return`
:host{display:block;width:100%;height:auto;min-height:0;container-type:inline-size;--bg:var(--ha-card-background,var(--card-background-color,#fff));--txt:var(--primary-text-color,#111);--mut:var(--secondary-text-color,#777);--pri:var(--primary-color,#03a9f4);--ok:var(--success-color,#4caf50);--warn:var(--warning-color,#ff9800);--err:var(--error-color,#f44336);--bord:color-mix(in srgb,var(--divider-color,#888) 65%,transparent);--pan:color-mix(in srgb,var(--bg) 92%,var(--pri) 8%)}*{box-sizing:border-box}button{font:inherit;color:inherit}ha-card{height:auto;overflow:hidden;color:var(--txt);background:radial-gradient(circle at 90% 0,color-mix(in srgb,var(--pri) 17%,transparent),transparent 34%),var(--bg);border:1px solid var(--bord);border-radius:var(--ha-card-border-radius,18px);box-shadow:var(--ha-card-box-shadow)}main{padding:clamp(10px,1.35cqw,16px);display:grid;gap:clamp(7px,1cqw,11px)}.panel{border:1px solid var(--bord);border-radius:14px;background:linear-gradient(135deg,color-mix(in srgb,var(--pan) 88%,var(--pri) 12%),var(--pan))}button{cursor:pointer}.tone-primary{color:var(--pri)}.tone-success{color:var(--ok)}.tone-warning{color:var(--warn)}.tone-error{color:var(--err)}.tone-neutral{color:var(--txt)}
.hero{position:relative;min-height:170px;padding:clamp(14px,1.7cqw,20px);display:flex;flex-direction:column;justify-content:space-between;gap:12px;overflow:hidden}.title{display:flex;align-items:center;gap:13px;z-index:2;max-width:62%}.ticon,.uicon,.ficon{display:grid;place-items:center;background:color-mix(in srgb,var(--pri) 16%,transparent);color:var(--pri)}.ticon{width:52px;height:52px;min-width:52px;border-radius:15px}.ticon ha-icon{--mdc-icon-size:30px}h1{margin:0;font-size:clamp(24px,3.2cqw,38px);line-height:1}.title p{margin:6px 0 0;color:var(--mut);font-size:clamp(13px,1.25cqw,16px)}.hero img{position:absolute;right:3%;top:5px;width:min(31%,245px);max-height:145px;object-fit:contain;filter:drop-shadow(0 10px 14px #0004)}.metrics{z-index:2;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.metric{border:1px solid var(--bord);border-radius:12px;background:color-mix(in srgb,var(--bg) 78%,transparent);padding:9px 10px;display:flex;align-items:center;gap:8px;min-width:0;min-height:54px;text-align:left}.metric>ha-icon{--mdc-icon-size:25px}.metric span,.dm span,.update span,.fcard>span:last-child{display:flex;flex-direction:column;gap:2px;min-width:0}.metric b,.dm b{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.metric small,.dm small,.update small,.fcard small,.ncard small{color:var(--mut)}
.net{display:grid;grid-template-columns:1fr 1fr;gap:clamp(7px,1cqw,11px)}.ncard{min-height:72px;padding:10px 14px;display:flex;align-items:center;gap:12px;text-align:left}.ncard>span{width:44px;height:44px;min-width:44px;border-radius:50%;border:3px solid currentColor;display:grid;place-items:center}.ncard>span ha-icon{--mdc-icon-size:23px}.ncard div{display:flex;flex-direction:column;gap:2px;min-width:0}.ncard b{color:var(--txt);font-size:clamp(17px,2cqw,23px);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.volume{min-height:150px;padding:12px 16px;display:grid;grid-template-columns:minmax(112px,.72fr) minmax(190px,1.35fr) minmax(105px,.65fr);gap:14px;align-items:center}.donut{width:min(125px,100%);aspect-ratio:1;border-radius:50%;background:conic-gradient(var(--pri) var(--p),color-mix(in srgb,var(--mut) 32%,transparent) 0);display:grid;place-items:center;position:relative}.donut:after{content:"";position:absolute;width:70%;aspect-ratio:1;border-radius:50%;background:var(--pan)}.donut>div{z-index:1;display:flex;flex-direction:column;align-items:center}.donut b{font-size:24px}.donut small{color:var(--mut)}.vdetail{border-left:1px solid var(--bord);padding-left:14px}.vdetail h2{margin:0 0 5px;font-size:20px}.vdetail>strong{font-size:20px}.vdetail em{color:var(--mut);font-style:normal;font-weight:500}.vdetail p{display:grid;grid-template-columns:1fr auto;gap:4px 12px;margin:9px 0 0;color:var(--mut);font-size:13px}.vdetail p b{color:var(--txt)}.vstatus{border:0;background:transparent;display:flex;flex-direction:column;align-items:center;gap:6px}.vstatus ha-icon{--mdc-icon-size:28px}
.drive{min-height:68px;padding:8px 13px;display:grid;grid-template-columns:minmax(105px,1.15fr) repeat(4,minmax(92px,1fr));align-items:stretch}.dtitle{display:flex;align-items:center;gap:9px}.dtitle ha-icon{--mdc-icon-size:27px}.dm{border:0;border-left:1px solid var(--bord);background:transparent;padding:6px 10px;display:flex;align-items:center;gap:7px;min-width:0;text-align:left}.dm>ha-icon{--mdc-icon-size:22px}.dm small{font-size:11px}.update{width:100%;min-height:68px;padding:9px 14px;display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:11px;text-align:left}.uicon{width:46px;height:46px;border-radius:13px}.uicon ha-icon{--mdc-icon-size:27px}.update span b{color:var(--txt);font-size:17px}.update>strong{padding:6px 10px;border:1px solid currentColor;border-radius:999px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:180px}
.foot{display:grid;grid-template-columns:repeat(3,1fr);gap:clamp(7px,1cqw,11px)}.fcard{min-height:80px;padding:10px 13px;display:flex;align-items:center;gap:11px;text-align:left;min-width:0}.ficon{width:50px;height:50px;min-width:50px;border-radius:14px}.ficon ha-icon{--mdc-icon-size:29px}.off .ficon{color:var(--err);background:color-mix(in srgb,var(--err) 15%,transparent)}.fcard small{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.fcard b{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
@container(max-width:700px){.hero{min-height:205px}.title{max-width:72%}.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.hero img{width:min(36%,210px);max-height:125px}.volume{grid-template-columns:110px minmax(0,1fr)}.vstatus{grid-column:1/-1;flex-direction:row;justify-content:flex-end}.drive{grid-template-columns:minmax(110px,1fr) repeat(2,minmax(90px,1fr))}.dtitle{grid-row:span 2}.dm{border-left:1px solid var(--bord)}.foot{grid-template-columns:repeat(3,minmax(0,1fr))}.fcard{padding:9px}.ficon{width:44px;height:44px;min-width:44px}.ficon ha-icon{--mdc-icon-size:26px}}
@container(max-width:470px){.title{max-width:100%}.hero img{opacity:.22;width:58%;right:-7%}.net{grid-template-columns:1fr 1fr}.ncard{padding:8px;gap:7px}.ncard>span{width:36px;height:36px;min-width:36px}.ncard>span ha-icon{--mdc-icon-size:20px}.volume{grid-template-columns:90px minmax(0,1fr);gap:9px;padding:10px}.donut{width:90px}.donut b{font-size:19px}.vdetail{padding-left:9px}.vdetail h2{font-size:17px}.vdetail>strong{font-size:16px}.drive{grid-template-columns:1fr 1fr}.dtitle{grid-column:1/-1;grid-row:auto;padding:4px}.dm{border-left:0;border-top:1px solid var(--bord)}.update>strong{display:none}.foot{grid-template-columns:repeat(3,minmax(0,1fr))}.fcard{justify-content:center}.fcard>span:last-child{display:none}.ficon{width:48px;height:48px;min-width:48px}}
`;}}
if(!customElements.get("nas-card"))customElements.define("nas-card",NasCard);window.customCards=window.customCards||[];if(!window.customCards.some(c=>c.type==="nas-card"))window.customCards.push({type:"nas-card",name:"NAS Card",description:"Theme-sensitive NAS dashboard card with native Home Assistant entity selectors.",preview:true,documentationURL:"https://github.com/BeGiBue/nas_card"});console.info(`%c NAS CARD %c v${NAS_CARD_VERSION} `,"background:#03a9f4;color:white;font-weight:700","background:#111;color:white");
